# Doc: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference

version: 2
updates:
  # NuGet dependencies - api
  - package-ecosystem: "nuget"
    directory: "."
    schedule:
      interval: "weekly"
      day: "monday"
      time: "19:00"
    target-branch: "master"
    open-pull-requests-limit: 0

  # npm dependencies - frontend
  - package-ecosystem: "npm"
    directory: "."
    schedule:
      interval: "weekly"
      day: "monday"
      time: "19:00"
    target-branch: "master"
    open-pull-requests-limit: 0