// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Gov.Jag.Pssg.Csa.Interfaces
{
    using Microsoft.Rest;
    using Models;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for Csuseizeditemsrequestedforreturns.
    /// </summary>
    public static partial class CsuseizeditemsrequestedforreturnsExtensions
    {
            /// <summary>
            /// Get entities from csu_seizeditemsrequestedforreturns
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='orderby'>
            /// Order items by property values
            /// </param>
            /// <param name='select'>
            /// Select properties to be returned
            /// </param>
            /// <param name='expand'>
            /// Expand related entities
            /// </param>
            public static MicrosoftDynamicsCRMcsuSeizeditemsrequestedforreturnCollection Get(this ICsuseizeditemsrequestedforreturns operations, IList<string> orderby = default(IList<string>), IList<string> select = default(IList<string>), IList<string> expand = default(IList<string>))
            {
                return operations.GetAsync(orderby, select, expand).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get entities from csu_seizeditemsrequestedforreturns
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='orderby'>
            /// Order items by property values
            /// </param>
            /// <param name='select'>
            /// Select properties to be returned
            /// </param>
            /// <param name='expand'>
            /// Expand related entities
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<MicrosoftDynamicsCRMcsuSeizeditemsrequestedforreturnCollection> GetAsync(this ICsuseizeditemsrequestedforreturns operations, IList<string> orderby = default(IList<string>), IList<string> select = default(IList<string>), IList<string> expand = default(IList<string>), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetWithHttpMessagesAsync(orderby, select, expand, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Get entities from csu_seizeditemsrequestedforreturns
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='orderby'>
            /// Order items by property values
            /// </param>
            /// <param name='select'>
            /// Select properties to be returned
            /// </param>
            /// <param name='expand'>
            /// Expand related entities
            /// </param>
            /// <param name='customHeaders'>
            /// Headers that will be added to request.
            /// </param>
            public static HttpOperationResponse<MicrosoftDynamicsCRMcsuSeizeditemsrequestedforreturnCollection> GetWithHttpMessages(this ICsuseizeditemsrequestedforreturns operations, IList<string> orderby = default(IList<string>), IList<string> select = default(IList<string>), IList<string> expand = default(IList<string>), Dictionary<string, List<string>> customHeaders = null)
            {
                return operations.GetWithHttpMessagesAsync(orderby, select, expand, customHeaders, CancellationToken.None).ConfigureAwait(false).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Add new entity to csu_seizeditemsrequestedforreturns
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// New entity
            /// </param>
            /// <param name='prefer'>
            /// Required in order for the service to return a JSON representation of the
            /// object.
            /// </param>
            public static MicrosoftDynamicsCRMcsuSeizeditemsrequestedforreturn Create(this ICsuseizeditemsrequestedforreturns operations, MicrosoftDynamicsCRMcsuSeizeditemsrequestedforreturn body, string prefer = "return=representation")
            {
                return operations.CreateAsync(body, prefer).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Add new entity to csu_seizeditemsrequestedforreturns
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// New entity
            /// </param>
            /// <param name='prefer'>
            /// Required in order for the service to return a JSON representation of the
            /// object.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<MicrosoftDynamicsCRMcsuSeizeditemsrequestedforreturn> CreateAsync(this ICsuseizeditemsrequestedforreturns operations, MicrosoftDynamicsCRMcsuSeizeditemsrequestedforreturn body, string prefer = "return=representation", CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.CreateWithHttpMessagesAsync(body, prefer, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Add new entity to csu_seizeditemsrequestedforreturns
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// New entity
            /// </param>
            /// <param name='prefer'>
            /// Required in order for the service to return a JSON representation of the
            /// object.
            /// </param>
            /// <param name='customHeaders'>
            /// Headers that will be added to request.
            /// </param>
            public static HttpOperationResponse<MicrosoftDynamicsCRMcsuSeizeditemsrequestedforreturn> CreateWithHttpMessages(this ICsuseizeditemsrequestedforreturns operations, MicrosoftDynamicsCRMcsuSeizeditemsrequestedforreturn body, string prefer = "return=representation", Dictionary<string, List<string>> customHeaders = null)
            {
                return operations.CreateWithHttpMessagesAsync(body, prefer, customHeaders, CancellationToken.None).ConfigureAwait(false).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get entity from csu_seizeditemsrequestedforreturns by key
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='csuSeizeditemsrequestedforreturnid'>
            /// key: csu_seizeditemsrequestedforreturnid of
            /// csu_seizeditemsrequestedforreturn
            /// </param>
            /// <param name='select'>
            /// Select properties to be returned
            /// </param>
            /// <param name='expand'>
            /// Expand related entities
            /// </param>
            public static MicrosoftDynamicsCRMcsuSeizeditemsrequestedforreturn SeizeditemsrequestedforreturnsByKey(this ICsuseizeditemsrequestedforreturns operations, System.Guid csuSeizeditemsrequestedforreturnid, IList<string> select = default(IList<string>), IList<string> expand = default(IList<string>))
            {
                return operations.SeizeditemsrequestedforreturnsByKeyAsync(csuSeizeditemsrequestedforreturnid, select, expand).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get entity from csu_seizeditemsrequestedforreturns by key
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='csuSeizeditemsrequestedforreturnid'>
            /// key: csu_seizeditemsrequestedforreturnid of
            /// csu_seizeditemsrequestedforreturn
            /// </param>
            /// <param name='select'>
            /// Select properties to be returned
            /// </param>
            /// <param name='expand'>
            /// Expand related entities
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<MicrosoftDynamicsCRMcsuSeizeditemsrequestedforreturn> SeizeditemsrequestedforreturnsByKeyAsync(this ICsuseizeditemsrequestedforreturns operations, System.Guid csuSeizeditemsrequestedforreturnid, IList<string> select = default(IList<string>), IList<string> expand = default(IList<string>), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.SeizeditemsrequestedforreturnsByKeyWithHttpMessagesAsync(csuSeizeditemsrequestedforreturnid, select, expand, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Get entity from csu_seizeditemsrequestedforreturns by key
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='csuSeizeditemsrequestedforreturnid'>
            /// key: csu_seizeditemsrequestedforreturnid of
            /// csu_seizeditemsrequestedforreturn
            /// </param>
            /// <param name='select'>
            /// Select properties to be returned
            /// </param>
            /// <param name='expand'>
            /// Expand related entities
            /// </param>
            /// <param name='customHeaders'>
            /// Headers that will be added to request.
            /// </param>
            public static HttpOperationResponse<MicrosoftDynamicsCRMcsuSeizeditemsrequestedforreturn> SeizeditemsrequestedforreturnsByKeyWithHttpMessages(this ICsuseizeditemsrequestedforreturns operations, System.Guid csuSeizeditemsrequestedforreturnid, IList<string> select = default(IList<string>), IList<string> expand = default(IList<string>), Dictionary<string, List<string>> customHeaders = null)
            {
                return operations.SeizeditemsrequestedforreturnsByKeyWithHttpMessagesAsync(csuSeizeditemsrequestedforreturnid, select, expand, customHeaders, CancellationToken.None).ConfigureAwait(false).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Update entity in csu_seizeditemsrequestedforreturns
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='csuSeizeditemsrequestedforreturnid'>
            /// key: csu_seizeditemsrequestedforreturnid of
            /// csu_seizeditemsrequestedforreturn
            /// </param>
            /// <param name='body'>
            /// New property values
            /// </param>
            public static void SeizeditemsrequestedforreturnsByKey1(this ICsuseizeditemsrequestedforreturns operations, System.Guid csuSeizeditemsrequestedforreturnid, MicrosoftDynamicsCRMcsuSeizeditemsrequestedforreturn body)
            {
                operations.SeizeditemsrequestedforreturnsByKey1Async(csuSeizeditemsrequestedforreturnid, body).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Update entity in csu_seizeditemsrequestedforreturns
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='csuSeizeditemsrequestedforreturnid'>
            /// key: csu_seizeditemsrequestedforreturnid of
            /// csu_seizeditemsrequestedforreturn
            /// </param>
            /// <param name='body'>
            /// New property values
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task SeizeditemsrequestedforreturnsByKey1Async(this ICsuseizeditemsrequestedforreturns operations, System.Guid csuSeizeditemsrequestedforreturnid, MicrosoftDynamicsCRMcsuSeizeditemsrequestedforreturn body, CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.SeizeditemsrequestedforreturnsByKey1WithHttpMessagesAsync(csuSeizeditemsrequestedforreturnid, body, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

            /// <summary>
            /// Update entity in csu_seizeditemsrequestedforreturns
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='csuSeizeditemsrequestedforreturnid'>
            /// key: csu_seizeditemsrequestedforreturnid of
            /// csu_seizeditemsrequestedforreturn
            /// </param>
            /// <param name='body'>
            /// New property values
            /// </param>
            /// <param name='customHeaders'>
            /// Headers that will be added to request.
            /// </param>
            public static HttpOperationResponse SeizeditemsrequestedforreturnsByKey1WithHttpMessages(this ICsuseizeditemsrequestedforreturns operations, System.Guid csuSeizeditemsrequestedforreturnid, MicrosoftDynamicsCRMcsuSeizeditemsrequestedforreturn body, Dictionary<string, List<string>> customHeaders = null)
            {
                return operations.SeizeditemsrequestedforreturnsByKey1WithHttpMessagesAsync(csuSeizeditemsrequestedforreturnid, body, customHeaders, CancellationToken.None).ConfigureAwait(false).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Delete entity from csu_seizeditemsrequestedforreturns
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='csuSeizeditemsrequestedforreturnid'>
            /// key: csu_seizeditemsrequestedforreturnid of
            /// csu_seizeditemsrequestedforreturn
            /// </param>
            /// <param name='ifMatch'>
            /// ETag
            /// </param>
            public static void SeizeditemsrequestedforreturnsByKey2(this ICsuseizeditemsrequestedforreturns operations, System.Guid csuSeizeditemsrequestedforreturnid, string ifMatch = default(string))
            {
                operations.SeizeditemsrequestedforreturnsByKey2Async(csuSeizeditemsrequestedforreturnid, ifMatch).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Delete entity from csu_seizeditemsrequestedforreturns
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='csuSeizeditemsrequestedforreturnid'>
            /// key: csu_seizeditemsrequestedforreturnid of
            /// csu_seizeditemsrequestedforreturn
            /// </param>
            /// <param name='ifMatch'>
            /// ETag
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task SeizeditemsrequestedforreturnsByKey2Async(this ICsuseizeditemsrequestedforreturns operations, System.Guid csuSeizeditemsrequestedforreturnid, string ifMatch = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.SeizeditemsrequestedforreturnsByKey2WithHttpMessagesAsync(csuSeizeditemsrequestedforreturnid, ifMatch, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

            /// <summary>
            /// Delete entity from csu_seizeditemsrequestedforreturns
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='csuSeizeditemsrequestedforreturnid'>
            /// key: csu_seizeditemsrequestedforreturnid of
            /// csu_seizeditemsrequestedforreturn
            /// </param>
            /// <param name='ifMatch'>
            /// ETag
            /// </param>
            /// <param name='customHeaders'>
            /// Headers that will be added to request.
            /// </param>
            public static HttpOperationResponse SeizeditemsrequestedforreturnsByKey2WithHttpMessages(this ICsuseizeditemsrequestedforreturns operations, System.Guid csuSeizeditemsrequestedforreturnid, string ifMatch = default(string), Dictionary<string, List<string>> customHeaders = null)
            {
                return operations.SeizeditemsrequestedforreturnsByKey2WithHttpMessagesAsync(csuSeizeditemsrequestedforreturnid, ifMatch, customHeaders, CancellationToken.None).ConfigureAwait(false).GetAwaiter().GetResult();
            }

    }
}
