// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Gov.Jag.Pssg.Csa.Interfaces
{
    using Microsoft.Rest;
    using Models;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for Csuvehicledetails.
    /// </summary>
    public static partial class CsuvehicledetailsExtensions
    {
            /// <summary>
            /// Get entities from csu_vehicledetails
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='orderby'>
            /// Order items by property values
            /// </param>
            /// <param name='select'>
            /// Select properties to be returned
            /// </param>
            /// <param name='expand'>
            /// Expand related entities
            /// </param>
            public static MicrosoftDynamicsCRMcsuVehicledetailCollection Get(this ICsuvehicledetails operations, IList<string> orderby = default(IList<string>), IList<string> select = default(IList<string>), IList<string> expand = default(IList<string>))
            {
                return operations.GetAsync(orderby, select, expand).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get entities from csu_vehicledetails
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='orderby'>
            /// Order items by property values
            /// </param>
            /// <param name='select'>
            /// Select properties to be returned
            /// </param>
            /// <param name='expand'>
            /// Expand related entities
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<MicrosoftDynamicsCRMcsuVehicledetailCollection> GetAsync(this ICsuvehicledetails operations, IList<string> orderby = default(IList<string>), IList<string> select = default(IList<string>), IList<string> expand = default(IList<string>), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetWithHttpMessagesAsync(orderby, select, expand, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Get entities from csu_vehicledetails
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='orderby'>
            /// Order items by property values
            /// </param>
            /// <param name='select'>
            /// Select properties to be returned
            /// </param>
            /// <param name='expand'>
            /// Expand related entities
            /// </param>
            /// <param name='customHeaders'>
            /// Headers that will be added to request.
            /// </param>
            public static HttpOperationResponse<MicrosoftDynamicsCRMcsuVehicledetailCollection> GetWithHttpMessages(this ICsuvehicledetails operations, IList<string> orderby = default(IList<string>), IList<string> select = default(IList<string>), IList<string> expand = default(IList<string>), Dictionary<string, List<string>> customHeaders = null)
            {
                return operations.GetWithHttpMessagesAsync(orderby, select, expand, customHeaders, CancellationToken.None).ConfigureAwait(false).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Add new entity to csu_vehicledetails
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// New entity
            /// </param>
            /// <param name='prefer'>
            /// Required in order for the service to return a JSON representation of the
            /// object.
            /// </param>
            public static MicrosoftDynamicsCRMcsuVehicledetail Create(this ICsuvehicledetails operations, MicrosoftDynamicsCRMcsuVehicledetail body, string prefer = "return=representation")
            {
                return operations.CreateAsync(body, prefer).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Add new entity to csu_vehicledetails
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// New entity
            /// </param>
            /// <param name='prefer'>
            /// Required in order for the service to return a JSON representation of the
            /// object.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<MicrosoftDynamicsCRMcsuVehicledetail> CreateAsync(this ICsuvehicledetails operations, MicrosoftDynamicsCRMcsuVehicledetail body, string prefer = "return=representation", CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.CreateWithHttpMessagesAsync(body, prefer, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Add new entity to csu_vehicledetails
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// New entity
            /// </param>
            /// <param name='prefer'>
            /// Required in order for the service to return a JSON representation of the
            /// object.
            /// </param>
            /// <param name='customHeaders'>
            /// Headers that will be added to request.
            /// </param>
            public static HttpOperationResponse<MicrosoftDynamicsCRMcsuVehicledetail> CreateWithHttpMessages(this ICsuvehicledetails operations, MicrosoftDynamicsCRMcsuVehicledetail body, string prefer = "return=representation", Dictionary<string, List<string>> customHeaders = null)
            {
                return operations.CreateWithHttpMessagesAsync(body, prefer, customHeaders, CancellationToken.None).ConfigureAwait(false).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get entity from csu_vehicledetails by key
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='csuVehicledetailid'>
            /// key: csu_vehicledetailid of csu_vehicledetail
            /// </param>
            /// <param name='select'>
            /// Select properties to be returned
            /// </param>
            /// <param name='expand'>
            /// Expand related entities
            /// </param>
            public static MicrosoftDynamicsCRMcsuVehicledetail VehicledetailsByKey(this ICsuvehicledetails operations, System.Guid csuVehicledetailid, IList<string> select = default(IList<string>), IList<string> expand = default(IList<string>))
            {
                return operations.VehicledetailsByKeyAsync(csuVehicledetailid, select, expand).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get entity from csu_vehicledetails by key
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='csuVehicledetailid'>
            /// key: csu_vehicledetailid of csu_vehicledetail
            /// </param>
            /// <param name='select'>
            /// Select properties to be returned
            /// </param>
            /// <param name='expand'>
            /// Expand related entities
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<MicrosoftDynamicsCRMcsuVehicledetail> VehicledetailsByKeyAsync(this ICsuvehicledetails operations, System.Guid csuVehicledetailid, IList<string> select = default(IList<string>), IList<string> expand = default(IList<string>), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.VehicledetailsByKeyWithHttpMessagesAsync(csuVehicledetailid, select, expand, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Get entity from csu_vehicledetails by key
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='csuVehicledetailid'>
            /// key: csu_vehicledetailid of csu_vehicledetail
            /// </param>
            /// <param name='select'>
            /// Select properties to be returned
            /// </param>
            /// <param name='expand'>
            /// Expand related entities
            /// </param>
            /// <param name='customHeaders'>
            /// Headers that will be added to request.
            /// </param>
            public static HttpOperationResponse<MicrosoftDynamicsCRMcsuVehicledetail> VehicledetailsByKeyWithHttpMessages(this ICsuvehicledetails operations, System.Guid csuVehicledetailid, IList<string> select = default(IList<string>), IList<string> expand = default(IList<string>), Dictionary<string, List<string>> customHeaders = null)
            {
                return operations.VehicledetailsByKeyWithHttpMessagesAsync(csuVehicledetailid, select, expand, customHeaders, CancellationToken.None).ConfigureAwait(false).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Update entity in csu_vehicledetails
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='csuVehicledetailid'>
            /// key: csu_vehicledetailid of csu_vehicledetail
            /// </param>
            /// <param name='body'>
            /// New property values
            /// </param>
            public static void VehicledetailsByKey1(this ICsuvehicledetails operations, System.Guid csuVehicledetailid, MicrosoftDynamicsCRMcsuVehicledetail body)
            {
                operations.VehicledetailsByKey1Async(csuVehicledetailid, body).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Update entity in csu_vehicledetails
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='csuVehicledetailid'>
            /// key: csu_vehicledetailid of csu_vehicledetail
            /// </param>
            /// <param name='body'>
            /// New property values
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task VehicledetailsByKey1Async(this ICsuvehicledetails operations, System.Guid csuVehicledetailid, MicrosoftDynamicsCRMcsuVehicledetail body, CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.VehicledetailsByKey1WithHttpMessagesAsync(csuVehicledetailid, body, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

            /// <summary>
            /// Update entity in csu_vehicledetails
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='csuVehicledetailid'>
            /// key: csu_vehicledetailid of csu_vehicledetail
            /// </param>
            /// <param name='body'>
            /// New property values
            /// </param>
            /// <param name='customHeaders'>
            /// Headers that will be added to request.
            /// </param>
            public static HttpOperationResponse VehicledetailsByKey1WithHttpMessages(this ICsuvehicledetails operations, System.Guid csuVehicledetailid, MicrosoftDynamicsCRMcsuVehicledetail body, Dictionary<string, List<string>> customHeaders = null)
            {
                return operations.VehicledetailsByKey1WithHttpMessagesAsync(csuVehicledetailid, body, customHeaders, CancellationToken.None).ConfigureAwait(false).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Delete entity from csu_vehicledetails
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='csuVehicledetailid'>
            /// key: csu_vehicledetailid of csu_vehicledetail
            /// </param>
            /// <param name='ifMatch'>
            /// ETag
            /// </param>
            public static void VehicledetailsByKey2(this ICsuvehicledetails operations, System.Guid csuVehicledetailid, string ifMatch = default(string))
            {
                operations.VehicledetailsByKey2Async(csuVehicledetailid, ifMatch).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Delete entity from csu_vehicledetails
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='csuVehicledetailid'>
            /// key: csu_vehicledetailid of csu_vehicledetail
            /// </param>
            /// <param name='ifMatch'>
            /// ETag
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task VehicledetailsByKey2Async(this ICsuvehicledetails operations, System.Guid csuVehicledetailid, string ifMatch = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.VehicledetailsByKey2WithHttpMessagesAsync(csuVehicledetailid, ifMatch, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

            /// <summary>
            /// Delete entity from csu_vehicledetails
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='csuVehicledetailid'>
            /// key: csu_vehicledetailid of csu_vehicledetail
            /// </param>
            /// <param name='ifMatch'>
            /// ETag
            /// </param>
            /// <param name='customHeaders'>
            /// Headers that will be added to request.
            /// </param>
            public static HttpOperationResponse VehicledetailsByKey2WithHttpMessages(this ICsuvehicledetails operations, System.Guid csuVehicledetailid, string ifMatch = default(string), Dictionary<string, List<string>> customHeaders = null)
            {
                return operations.VehicledetailsByKey2WithHttpMessagesAsync(csuVehicledetailid, ifMatch, customHeaders, CancellationToken.None).ConfigureAwait(false).GetAwaiter().GetResult();
            }

    }
}
