// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Gov.Jag.Pssg.Csa.Interfaces.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Collection of csu_seizeditemsrequestedforreturn
    /// </summary>
    /// <remarks>
    /// Microsoft.Dynamics.CRM.csu_seizeditemsrequestedforreturnCollection
    /// </remarks>
    public partial class MicrosoftDynamicsCRMcsuSeizeditemsrequestedforreturnCollection
    {
        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftDynamicsCRMcsuSeizeditemsrequestedforreturnCollection
        /// class.
        /// </summary>
        public MicrosoftDynamicsCRMcsuSeizeditemsrequestedforreturnCollection()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftDynamicsCRMcsuSeizeditemsrequestedforreturnCollection
        /// class.
        /// </summary>
        public MicrosoftDynamicsCRMcsuSeizeditemsrequestedforreturnCollection(IList<MicrosoftDynamicsCRMcsuSeizeditemsrequestedforreturn> value = default(IList<MicrosoftDynamicsCRMcsuSeizeditemsrequestedforreturn>))
        {
            Value = value;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public IList<MicrosoftDynamicsCRMcsuSeizeditemsrequestedforreturn> Value { get; set; }

    }
}
