// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Gov.Jag.Pssg.Csa.Interfaces.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Microsoft.Dynamics.CRM.complexcontrol
    /// </summary>
    public partial class MicrosoftDynamicsCRMcomplexcontrol
    {
        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftDynamicsCRMcomplexcontrol class.
        /// </summary>
        public MicrosoftDynamicsCRMcomplexcontrol()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftDynamicsCRMcomplexcontrol class.
        /// </summary>
        public MicrosoftDynamicsCRMcomplexcontrol(string versionnumber = default(string), System.Guid? _organizationidValue = default(System.Guid?), System.Guid? complexcontrolid = default(System.Guid?), bool? ismanaged = default(bool?), int? version = default(int?), string name = default(string), int? componentstate = default(int?), int? type = default(int?), string complexcontrolxml = default(string), System.DateTimeOffset? overwritetime = default(System.DateTimeOffset?), string introducedversion = default(string), System.Guid? complexcontrolidunique = default(System.Guid?), System.Guid? solutionid = default(System.Guid?), string description = default(string), MicrosoftDynamicsCRMorganization organizationid = default(MicrosoftDynamicsCRMorganization))
        {
            Versionnumber = versionnumber;
            this._organizationidValue = _organizationidValue;
            Complexcontrolid = complexcontrolid;
            Ismanaged = ismanaged;
            Version = version;
            Name = name;
            Componentstate = componentstate;
            Type = type;
            Complexcontrolxml = complexcontrolxml;
            Overwritetime = overwritetime;
            Introducedversion = introducedversion;
            Complexcontrolidunique = complexcontrolidunique;
            Solutionid = solutionid;
            Description = description;
            Organizationid = organizationid;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "versionnumber")]
        public string Versionnumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "_organizationid_value")]
        public System.Guid? _organizationidValue { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "complexcontrolid")]
        public System.Guid? Complexcontrolid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ismanaged")]
        public bool? Ismanaged { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "version")]
        public int? Version { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "componentstate")]
        public int? Componentstate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public int? Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "complexcontrolxml")]
        public string Complexcontrolxml { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "overwritetime")]
        public System.DateTimeOffset? Overwritetime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "introducedversion")]
        public string Introducedversion { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "complexcontrolidunique")]
        public System.Guid? Complexcontrolidunique { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "solutionid")]
        public System.Guid? Solutionid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "organizationid")]
        public MicrosoftDynamicsCRMorganization Organizationid { get; set; }

    }
}
