// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Gov.Jag.Pssg.Csa.Interfaces.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Microsoft.Dynamics.CRM.lookupmapping
    /// </summary>
    public partial class MicrosoftDynamicsCRMlookupmapping
    {
        /// <summary>
        /// Initializes a new instance of the MicrosoftDynamicsCRMlookupmapping
        /// class.
        /// </summary>
        public MicrosoftDynamicsCRMlookupmapping()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MicrosoftDynamicsCRMlookupmapping
        /// class.
        /// </summary>
        public MicrosoftDynamicsCRMlookupmapping(System.DateTimeOffset? createdon = default(System.DateTimeOffset?), System.DateTimeOffset? modifiedon = default(System.DateTimeOffset?), System.Guid? _modifiedonbehalfbyValue = default(System.Guid?), System.Guid? solutionid = default(System.Guid?), bool? ismanaged = default(bool?), int? processcode = default(int?), System.Guid? _columnmappingidValue = default(System.Guid?), int? statecode = default(int?), int? statuscode = default(int?), System.Guid? lookupmappingid = default(System.Guid?), System.Guid? _createdbyValue = default(System.Guid?), string lookupattributename = default(string), System.Guid? _transformationparametermappingidValue = default(System.Guid?), string lookupentityname = default(string), System.Guid? _createdonbehalfbyValue = default(System.Guid?), System.Guid? _modifiedbyValue = default(System.Guid?), int? lookupsourcecode = default(int?), string introducedversion = default(string), int? componentstate = default(int?), System.Guid? lookupmappingidunique = default(System.Guid?), System.DateTimeOffset? overwritetime = default(System.DateTimeOffset?), MicrosoftDynamicsCRMsystemuser modifiedby = default(MicrosoftDynamicsCRMsystemuser), MicrosoftDynamicsCRMtransformationparametermapping transformationparametermappingid = default(MicrosoftDynamicsCRMtransformationparametermapping), MicrosoftDynamicsCRMsystemuser createdby = default(MicrosoftDynamicsCRMsystemuser), MicrosoftDynamicsCRMsystemuser modifiedonbehalfby = default(MicrosoftDynamicsCRMsystemuser), MicrosoftDynamicsCRMsystemuser createdonbehalfby = default(MicrosoftDynamicsCRMsystemuser), MicrosoftDynamicsCRMcolumnmapping columnmappingid = default(MicrosoftDynamicsCRMcolumnmapping))
        {
            Createdon = createdon;
            Modifiedon = modifiedon;
            this._modifiedonbehalfbyValue = _modifiedonbehalfbyValue;
            Solutionid = solutionid;
            Ismanaged = ismanaged;
            Processcode = processcode;
            this._columnmappingidValue = _columnmappingidValue;
            Statecode = statecode;
            Statuscode = statuscode;
            Lookupmappingid = lookupmappingid;
            this._createdbyValue = _createdbyValue;
            Lookupattributename = lookupattributename;
            this._transformationparametermappingidValue = _transformationparametermappingidValue;
            Lookupentityname = lookupentityname;
            this._createdonbehalfbyValue = _createdonbehalfbyValue;
            this._modifiedbyValue = _modifiedbyValue;
            Lookupsourcecode = lookupsourcecode;
            Introducedversion = introducedversion;
            Componentstate = componentstate;
            Lookupmappingidunique = lookupmappingidunique;
            Overwritetime = overwritetime;
            Modifiedby = modifiedby;
            Transformationparametermappingid = transformationparametermappingid;
            Createdby = createdby;
            Modifiedonbehalfby = modifiedonbehalfby;
            Createdonbehalfby = createdonbehalfby;
            Columnmappingid = columnmappingid;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "createdon")]
        public System.DateTimeOffset? Createdon { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "modifiedon")]
        public System.DateTimeOffset? Modifiedon { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "_modifiedonbehalfby_value")]
        public System.Guid? _modifiedonbehalfbyValue { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "solutionid")]
        public System.Guid? Solutionid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ismanaged")]
        public bool? Ismanaged { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "processcode")]
        public int? Processcode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "_columnmappingid_value")]
        public System.Guid? _columnmappingidValue { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "statecode")]
        public int? Statecode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "statuscode")]
        public int? Statuscode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lookupmappingid")]
        public System.Guid? Lookupmappingid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "_createdby_value")]
        public System.Guid? _createdbyValue { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lookupattributename")]
        public string Lookupattributename { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "_transformationparametermappingid_value")]
        public System.Guid? _transformationparametermappingidValue { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lookupentityname")]
        public string Lookupentityname { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "_createdonbehalfby_value")]
        public System.Guid? _createdonbehalfbyValue { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "_modifiedby_value")]
        public System.Guid? _modifiedbyValue { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lookupsourcecode")]
        public int? Lookupsourcecode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "introducedversion")]
        public string Introducedversion { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "componentstate")]
        public int? Componentstate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lookupmappingidunique")]
        public System.Guid? Lookupmappingidunique { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "overwritetime")]
        public System.DateTimeOffset? Overwritetime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "modifiedby")]
        public MicrosoftDynamicsCRMsystemuser Modifiedby { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "transformationparametermappingid")]
        public MicrosoftDynamicsCRMtransformationparametermapping Transformationparametermappingid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "createdby")]
        public MicrosoftDynamicsCRMsystemuser Createdby { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "modifiedonbehalfby")]
        public MicrosoftDynamicsCRMsystemuser Modifiedonbehalfby { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "createdonbehalfby")]
        public MicrosoftDynamicsCRMsystemuser Createdonbehalfby { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "columnmappingid")]
        public MicrosoftDynamicsCRMcolumnmapping Columnmappingid { get; set; }

    }
}
